[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zaibatsu"
version = "0.2.1"
description = "A cyberpunk-themed terminal 3D cityscape process monitor"
readme = "README.md"
authors = [
    { name = "DIIZZY" }
]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Topic :: System :: Monitoring",
]
requires-python = ">=3.8"
dependencies = [
    "psutil>=5.9.0",
    "rich>=13.0.0"
]

[project.urls]
Homepage = "https://github.com/DIIZZYFPS/Zaibatsu"

[project.scripts]
zaibatsu = "zaibatsu.cli:main"

[tool.setuptools.packages.find]
include = ["zaibatsu*"]
